
project_id = "lpwvhyawvxibtuxfhitx"

[functions.telegram-chat]
verify_jwt = false

[functions.yandex-auth]
verify_jwt = false

[scripts.before_supabase_migrations]
location = "./supabase/scripts/before-supabase-migrations.sql"
